theme: osuny
_merge: deep
params:
  additional_csp: app.cal.com 'unsafe-inline'
  breadcrumb:
    position: footer
  components:
    lightbox:
      disabled: false
      in_hero:
        disabled: true
  home:
    head:
      title: site
  logo:
    header: '/assets/images/logo-osuny.svg'
    footer: '/assets/images/logo-osuny.svg'
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  posts:
    index:
      layout: grid
    single:
      options:
        updated_at: false
  projects:
    index:
      options:
        summary: false
    share_links:
      enabled: false
  search:
    active: true
    positions:
      - footer
  seo:
    title:
      separator: "•"
  summary:
    position: hero
